### ISSUE TITLE
Drupal 9 - Call to private method parseName() in EuropaComponentLibraryLoader.php

### ISSUE THREAD

**Issue by didierdemaeyer** [openeuropa/ecl-twig-loader#27]
In Drupal 9 the Twig `FilesystemLoader::parseName()` method has changed from `protected` to `private`. This method is called in the `EuropaComponentLibraryLoader.php`

```
Error: Call to private method Twig\Loader\FilesystemLoader::parseName() from context 'OpenEuropa\Twig\Loader\EuropaComponentLibraryLoader' in OpenEuropa\Twig\Loader\EuropaComponentLibraryLoader->findTemplate() (line 71 of /var/www/html/vendor/openeuropa/ecl-twig-loader/src/Loader/EuropaComponentLibraryLoader.php)
```

https://api.drupal.org/api/drupal/vendor%21twig%21twig%21src%21Loader%21FilesystemLoader.php/8.9.x

https://api.drupal.org/api/drupal/vendor%21twig%21twig%21src%21Loader%21FilesystemLoader.php/9.0.x

**Comment by brummbar** [comment]
Fixed in #31 .
